#pragma once
#ifndef __P_SCHEDULEEXTENSION__
#define __P_SCHEDULEEXTENSION__


#if !defined(AVR) && !defined(ESP32) && !defined(ARDUINO_RASPBERRY_PI_PICO) // Pico hinzugefügt 22.5.2025 gebo
#error Platform is not supported
#error Platform is not supported
#endif

#include <MLLExtension.h>
         
//#define _PeterDebug				// allgemeiner Debug


#ifdef _PeterDebug 
	#ifdef __FlashStringHelper		// Dank Jürgen (jueff) gibt es jetzt keinen Kompilerfehler mehr mit Streaming. 
		#undef __FlashStringHelper
	#endif
	#include <Streaming.h> 	  // https://github.com/janelia-arduino/Streaming
#endif


/*
P_ScheduleExtension 
V 0.01 	17.05.2024	Test mit 5 Parametern (Dest1, TestN, enableCh (SI_1), start und end) Mit Zufallszeit fest im Programm (x_zufall = 15).
V 0.02 	20.05.2024	Debug-Ausgabe hinzu.
V 0.03 	20.05.2024	Zufallswert über Variable aus Prog-Gen. 
V 0.04	29.05.2024	Neue Version: Aufruf-Parameter:								
					<= nicht realisiert, Parameterart verworfen!
V 0.05	17.06.2024  Eingabe über Uhrzeit. Damit neue Parameter:	
						dstVar1				Erste Variable			Variable
						dstVarN				Letzte Variable			Variable
						enableCh			SI_1					Nummer der Enable Eingangs
						start_Std			Start-Stunde			0 - 23
						start_Min			Start-Minutes			0 - 59
						end_Std				Ende-Stunde				0 - 23
						end_Min				Ende.Minute				0 - 59
						zufall				Zufall-Tick				0 - 99
					Umrechnung der Uhrzeit in Ticks erledigt.
V 0.06	01.07.2024	Erste funktionierende Realisierung.
					Uhr2Tick Funktion geprüft. Ok!
					Einzelfunktion mit einer Variablen geprüft. Ok
V 0.07	04.07.2024	Bei mehreren Variablen werden nicht immer alle geschaltet. Sie werden direkt hintereinander geschaltet.
V 0.08	07.07.2024	Jetzt werden alle Varablen geschaltet. Aber immer noch schnell in Random-Art.
V 0.09	09.07.2024	SwitchVal Überlauf/negativer Wert wird jetzt umgerechnet, alledings in der gleichen DatState.
V 0.10	21.07.2024	Eingeschränkte Funktion: Mehrere Objekte schalten fast gleichzeitig (Haus1 ... Haus5).	
					Hinweis: Minimale Schaltzeit 1 Tick entspricht min. 3 Minuten!
V 0.11	25.08.2024	Umstellung auf neue Zeitrechnung. Mehrere Objekte werden aber fast gleichzeitig geschaltet.
V 0.12	28.08.2024	Prüfung der Schaltzeiten bei CalcSwitchVal, nicht befriedigend.
V 0.13	09.09.2024	Ist die Zeit zwischen ein und aus kleiner als der Zufallswert, wird 2/3 der Zeitdifferenz als Zufallswert verwendet.
V 0.14	16.10.2024	Debug erweitert. Ergebnis von CalcSwitchVal konnte > 512 sein, damit wurde eine Blockade ausgelöst.
					Probleme bei mehreren Varablen.
V 0.15	17.10.2024	Tests. Bei kurzer Schaltdifferenz wurde manchmal ein Schaltpunkt übersprungen.			
V 0.16	21.10.2024	Neuer Umrechnungsfaktor, wenn Zufall > Schaltdifferenz (Wert zwischen ein und aus bzw. aus und ein). 
					Beta-Version 1
V 0.17 	25.10.2024	Fehler bei der Abfrage nach Objekten (beginnen mit 0 nicht 1). Dadurch schalten 2 Objekte gleichzeitig.
					Debugausgabe, wenn Zufall programmtechnisch gekürzt wird.
					Beta-Version 2
V 0.18	05.01.2025	Debuging: Dank Jürgen (jueff) gibt es jetzt keinen Kompilerfehler mehr mit Streaming.
					Debuging: Wenn Zufall verkürzt wird, LED mit ausgeben.
					Variablendefinition aus Modulen herausgenommen, da Probleme mit ESP32.
V 0.19	29.06.2025	DstVar global definiert.
					Raspberry Pico hinzugefügt. Danke Gerald.
V 0.20	25.08.2025	Bei einem Neustart wird ein alter Einschaltbefehl sofort aktiviert. Beispiel: die LED soll um 8 Uhr angehen. Bisher musste ein mal
					Mitternacht abgewartet werden, bis der Schaltauftrag aktiviert wurde. Jetzt passiert es nach dem Reset.
					Nicht mehr benötigte Debug-Ausgaben entfernt.
					Variablen wieder bei den Funktionen.
V 0.21  03.12.2025	Übergabe-Parameter DstVar* und enableCh wahlweise 8 oder 16 Bit (DatVar hat dann 16 Bit bei ESP32 & RP20, 8Bit bei Nano)
					Korrektur der Abarbeitung von mehreren Objekten.
					Debugausgabe "SchaltzeitInfo" angepasst.
					Proc_Schedule: Wenn xZufall == 0 ist, wird eine Zwangspause zwischen 2 Schaltungen eingefügt von 100 mSec.
V 0.22  06.03.2026	MobaLedLib.properties angepasst an pyMobaLedLib ab Version 7.1.6 (Danke Harold).

				
ToDo:

				
		
*/
#ifdef _PeterDebug
	#define MyProg_MSG "0.21"		// Debugausgabe der Version
#endif
/*
Definition in InitDefs.h:
enum DayState_E : uint8_t	// --> don't change the sequence
    {
    Unknown = 0,
    SunSet  = 1,  	// 12 - 24 Uhr   
    SunRise = 2		// 0 Uhr - 12 Uhr Sonnenaufgang
	}
	
// Results generated by Get_getInputut()
#define INP_OFF            0b00000000
#define INP_ON             0b00000011
#define INP_TURNED_ON      0b00000001
#define INP_TURNED_OFF     0b00000010
#define INP_INIT_OFF       0b00000110
 Es ist NICHT moeglich den Ausgang einer Logic Funktion mehrfach zu verwenden weil dadurch
 Zustaende verloren gehen. Die Eingaenge haben 4 verschiedene Zustaende
   INP_OFF            B00000000
   INP_ON             B00000011
   INP_TURNED_ON      B00000001
   INP_TURNED_OFF     B00000010
                              ^
 Die Logic Funktion setzt nur das Letzte Bit.
 Der vorangegabgegangene Zustand wird im Bit mit der Wertigkeit 2 gespeichert.
 Dieses Bit wird am einde einer Updateschleife gesetzt.
 Wenn mehrere Logic Funktionen in die gleiche Variable schreiben, dann wird der Letzte Zustand
 nicht richtig gesetzt => INP_TURNED_ON / _OFF geht verloren ;-(
*/



// Defines für my_FirstLedStatus
	#define myLedOn 1					// LED-Status ist ein
	#define myLedOff 2					// LED-Status ist aus
	#define myLedUnKnow 0				// LED-Status ist unbekannt


#ifndef inch_t							// 26.11.2025 Jürgen
#define inch_t uint8_t
#endif

class P_ScheduleExtension : public MLLExtension
{
private:
	inch_t dstVar1;								// Übergabeparameter 1.LED					// 26.11.2025 Jürgen
	inch_t dstVarN;								// Übergabeparameter letzte LED				// 26.11.2025 Jürgen
	inch_t enableCh;							// Übergabeparameter SI_1					// 26.11.2025 Jürgen
	uint8_t start_Std;							// Übergabeparameter Start-Stunde
	uint8_t start_Min;							// Übergabeparameter Start-Minute
	uint8_t end_Std;							// Übergabeparameter Ende-Stunde
	uint8_t end_Min;							// Übergabeparameter Ende-Minute
	uint8_t zufall;								// Übergabeparameter Zufall-Ticks
	boolean neuStart = true;					// NeuStart Flag V0.20
	
	uint16_t my_start;							// interner Startwert (Zeit umgerechnet)
	uint16_t my_end;							// interner Endwert (Zeit umgerechnet)
	uint8_t my_FirstLedStatus = myLedOff;   	// interner Status der ersten LED

	uint16_t SwitchVal = 0; 					// Zeit-Tick zum schalten
	uint8_t ToDoCnt = 0;						// Anzahl Elemente zum schalten
	uint8_t ToDoCntSum = 0;	
	uint16_t MyAktTime = 0;						// P_Schedule interner Timer, abgeleitet von Darkness & DayState
	uint16_t z_diff = 0;
	uint16_t neuZufall = 0;					// Für Debugausgabe 'Zufall-Wert verkürzt'

#ifdef _PeterDebug

	uint8_t orgZufall = 0;						// Für Debugausgabe 'Zufall-Wert verkürzt'
#endif	
	inch_t DstVar ;								// 26.11.2025 Jürgen für LongInp 

	public:
	// Constructor
	//-----------------------------------------------------------------------------------------------
  P_ScheduleExtension(inch_t dstVar1, inch_t dstVarN, inch_t enableCh, uint8_t start_Std, uint8_t start_Min, uint8_t end_Std, uint8_t end_Min, uint8_t zufalltick )  
	//-----------------------------------------------------------------------------------------------
  {
	this->dstVar1 = dstVar1;
    this->dstVarN = dstVarN;
    this->enableCh = enableCh;
    this->start_Std = start_Std;
    this->end_Std = end_Std;
	this->start_Min = start_Min;
    this->end_Min = end_Min;
	this->zufall = zufalltick;
	this->neuZufall = zufalltick;				// 28.11.2025
	this->neuStart = true;						// Neustart ist im Constructor aktiviert. V0.20
#ifdef _PeterDebug
	orgZufall = zufalltick;						// Damit im Debug der Originalwert angezeigt werden kann, wenn Zufall verkürzt wird.
#endif
	my_start = Uhr2Tick(start_Std, start_Min);	// Startzeit umrechnen Rückgabe 
	my_end = Uhr2Tick(end_Std, end_Min);		// Endzeit umrechnen  Rückgabe 

	// Ist der Zufallswert > als die Schaltzeit, so wird als Zufall durch 2.5 geteilt verwendet.
	// Sonst bleibt u.U. die LED dauernd an oder aus.
	if (my_start < my_end)
	{
		z_diff = (my_end - my_start);
		if (z_diff / 2 <= zufall)
		{
			zufall = (z_diff * 2) / 5;
			neuZufall = zufall;
		}
		z_diff = ((my_start + 512) - my_end);
		if (z_diff / 2 <= zufall)
		{
			zufall = (z_diff * 2) / 5;
			neuZufall = zufall;
		}	
	} else {
		z_diff = 512 - my_start;
		z_diff = z_diff + my_end;
		if (z_diff / 2 <= zufall)
		{
			zufall = (z_diff * 2) / 5;
			neuZufall = zufall;
		}
	}
	my_FirstLedStatus = myLedOff;				// Aktueller LED-Status (an/aus) der ersten LED (dstVar1)
  }


	private:
	
#ifdef _PeterDebug	
	uint8_t Delta_ToDoCnt = 0;					// Unnötige Ausgaben gleicher Tick's unterbinden.
	uint16_t Delta_MyAktTime = 0;				// Unnötige Ausgaben gleicher Tick's unterbinden.
	uint8_t flagMitternacht = 0;				// Mitternacht ausgeben
	uint16_t Minutes ;
	
	//---------------
	void AktUhrzeit()
	//---------------
	// Debug-Ausgabe der aktuellen Zeit
	{
		if (Delta_MyAktTime != MyAktTime)
		{
			Minutes = ((uint32_t)MyAktTime * 24*60) / 512;		// 0.19
			Serial << "P_S- " << "+Uhrzeit: " <<  _WIDTHZ(Minutes/60,2) << ":" <<  _WIDTHZ(Minutes%60,2) << " MyAktTime " << MyAktTime << " Darkness: " << Darkness << " DayState " << DayState << endl;
			Delta_MyAktTime = MyAktTime;
		}
	}
	
	//---------------
	void SchaltzeitInfo(uint8_t xLed, uint8_t xAnAus, uint8_t xZufall)
	//---------------
	// Debug-Ausgabe der aktuellen Zeit				// 02.12.2025
	{
			Minutes = ((uint32_t)MyAktTime * 24*60) / 512;	// 0.19
			if (xAnAus == myLedOn)
			{
				Serial << "P_S- ++Schaltzeit: " <<  _WIDTHZ(Minutes/60,2) << ":" <<  _WIDTHZ(Minutes%60,2) << " Soll Ein: " <<  _WIDTHZ(start_Std,2) << ":" << _WIDTHZ(start_Min,2) <<  " Zufall: " << _WIDTH(zufall,3) <<  " xZufall: " << _WIDTH(xZufall,3) <<  " - LED: " << _WIDTH(xLed,4) << " Zustand: "  << xAnAus  << endl;
			} else {
				Serial << "P_S- --Schaltzeit: " <<  _WIDTHZ(Minutes/60,2) << ":" <<  _WIDTHZ(Minutes%60,2) << " Soll Aus: " <<  _WIDTHZ(end_Std,2) << ":" << _WIDTHZ(end_Min,2) <<  " Zufall: " << _WIDTH(zufall,3) <<  " xZufall: " << _WIDTH(xZufall,3) << " - LED: " << _WIDTH(xLed,4) << " Zustand: "  << xAnAus << endl;
			}
	}
#endif

	//--------------------------------------
	void Pausentimer()												// 02.12.2025
	//--------------------------------------
	// Wenn xZufall == 0 ist, wird eine Zwangspause zwischen 2 Schaltungen eingefügt von 100 mSec.
	{
		unsigned long pTime1 = millis();
		unsigned long pTime2 = pTime1 + 100;
		do // Schleife für die Verzögerungszeit
		{  //   
			pTime1 = millis();
		} while (pTime1 < pTime2);
	}
	
	
	//--------------------------------------
	uint8_t P_RundenMinTakt(uint8_t Minuten)			
	//--------------------------------------
	// Teile Minuten durch 3 und runde.
	// Das Runden der Minuten geschieht aus Speicherplatz-Gründen sehr einfach.
	{
		uint8_t minuteRund = 0;
		minuteRund = Minuten/3;
		if((minuteRund % 3) >= 2) minuteRund++;
		return minuteRund;
 	}
	
	//--------------------------------------------------
	uint16_t Uhr2Tick( uint8_t x_stunde, uint8_t x_minute)
	//--------------------------------------------------
	// Umrechnung der Uhrzeit in MLL-Ticks 
	{
		uint16_t takt = 0;
		takt = x_stunde * 21;
		if (x_stunde > 2) takt ++;
		if (x_stunde > 6) takt ++;
		if (x_stunde > 10) takt ++;
		if (x_stunde > 12) takt ++;
		if (x_stunde > 13) takt ++;
		if (x_stunde > 17) takt ++;
		if (x_stunde > 21) takt ++;
		takt = takt + P_RundenMinTakt(x_minute);
		if (x_minute > 29) takt ++;
		return takt;
	}
	
	//--------------------------------------
	void CalcSwitchVal( uint8_t LedIs_OnOff)
	//--------------------------------------
	// Schaltzeit durch "Zufall" ermitteln. 
	// Es werden 512 hinzugezählt, um einen negativen Übelauf (Schaltezit - Zufall) zu umgehen.
	// Nach der Rundung werden diese wieder abgezogen. Ist das Ergebnis < 512 ist es der gerechnete neue Schaltwert.
	{
		uint16_t tempSchalt = 0;
		if (LedIs_OnOff == myLedOff)				// LED ist Off  -- Start wird berechnet
		{
			SwitchVal = random(512 + my_start - zufall, 512 + my_start + zufall);
		} 
		else 
		{											// LED ist On -- Ende wird berechnet
			SwitchVal = random(512 + my_end - zufall, 512 + my_end + zufall);
		}
		if (SwitchVal >= 512)
		{
			SwitchVal = SwitchVal - 512;
			if (SwitchVal >= 512)
			{
				SwitchVal = SwitchVal - 512;
			}
			if (SwitchVal == 0)
			{
				SwitchVal = 1;
			}
		}
		else
		{
			SwitchVal = SwitchVal;		// Unnötig, nur zur Klarheit.
		}
		if (neuStart == true) {						// V0.20 Wenn NeuStart aktiv, dann prüfen, ob Einschalt-Zeitpunkt vorher war, aber Ausschaltpunkt noch nicht erreicht.
			if (my_start < 256) {					// Start vor Mittag (12:00)
				if (my_end > 256) {					// Ende nach Mittag (12:00)
					SwitchVal = MyAktTime + 1;		// Zur Sicherheit 1 MInute zugeben zu aktueller Schaltzeit.
				}	
			}
			neuStart = false;						// NeuStart-Flag zurücksetzen, da nur einmal benötigt.
		}
	}
	

	//------------------------------------------
	void Proc_ScheduleMyTime(MobaLedLib_C& mobaLedLib)
	//------------------------------------------
	// Neue MLL-Zeitrechnung aus Darkness & DayState ->  0/511 = Mitternacht, 256 = 12  Uhr Mittag
	// Wird regelmässig über LOOP aufgerufen.
	{
		if (DayState == SunSet)		// 12 - 24 Uhr		Daystate == 2	Darkness 0 - 255 	MyAktTime 257 - 512
		{
			MyAktTime = Darkness + 256;
		} else {					// 0 - 12 Uhr		DayState == 1	Darkness 255 - 0	MyAktTime 0 - 256
			MyAktTime = 256 - Darkness;
		}
//		AktUhrzeit(); 
	}


	//------------------------------------------
	void Proc_Schedule(MobaLedLib_C& mobaLedLib)
	//------------------------------------------
	{
		inch_t DstVar1;
		inch_t DstVarN;
		uint8_t nRandom;
		uint8_t xZufall = 2;
		uint16_t xDiff;
		uint8_t getInput;			// = mobaLedLib.Get_Input(enableCh); 		// Input LED-Nummer ????
				DstVar1 = dstVar1;
				DstVarN = dstVarN;
	
		getInput = mobaLedLib.Get_Input(enableCh); 		// Input #InCh --> bringt 3 zurück
		if (Inp_Is_On(getInput))
		{
			if (ToDoCnt == 0)  
			{
				ToDoCntSum = 0;
				for (DstVar = DstVar1; DstVar <= DstVarN; DstVar ++)	// Zählen der aktiven LED's	// 0.19
				{
						ToDoCnt ++;
						ToDoCntSum ++;						// 02.12.2025
				}
				CalcSwitchVal(my_FirstLedStatus);
			}
			
			
			if (ToDoCnt > 0)  								// 02.12.2025
			{
				if (DstVarN - DstVar1 > 0)
				{
					xZufall = zufall / ToDoCntSum  ;		// Sind mehrere Objekte vorhanden, so wird der geforderte Zufallswert duch die Anzahl der Objekte. 28.11.2025
					if (my_end > my_start)					// my_start: 8:00 (170) , my_end: 10:00 (213) = 43
					{
						xDiff = my_end - my_start;
					}
					else	// my_end < my_start			// my_start: 10:00 (213), my_end: 8:00 (170) = 
					{
						xDiff = my_start - my_end;
						xDiff = xDiff * -1;
					}
					if (xDiff <= (zufall * 2))
					{
						xZufall = 1;
					}
					if (xDiff <= ToDoCntSum ) 				// 28.11.2025
					{
						xZufall = 0;
					}	
				}
				else
				{
					xZufall = 0;							// Bei nur einem Objekt ist die Berechnung nicht notwendig.
				}
						
				nRandom = random8(ToDoCnt);
				if (my_FirstLedStatus == myLedOff)			// LED ist noch aus
				{
					for ( DstVar = DstVar1; DstVar <= DstVarN; DstVar ++)
					{
						if ((MyAktTime == SwitchVal))
						{
							if (mobaLedLib.Get_Input( DstVar) == INP_OFF || mobaLedLib.Get_Input( DstVar) == INP_TURNED_OFF)
							{
								if (nRandom-- == 0)
								{
#ifdef _PeterDebug
									SchaltzeitInfo( DstVar, myLedOn, xZufall);
#endif		
									mobaLedLib.Set_Input(DstVar,1);
									if (xZufall == 0)		// 02.12.2025
									{
										Pausentimer();		// 02.12.2025
									}
									ToDoCnt --;
									if (ToDoCnt > 0)
									{
										SwitchVal = SwitchVal + xZufall;
										if (SwitchVal > 511)
										{
											SwitchVal = xZufall;
										}
									}
								} 
							} 
						}
					}
				}
				else    									// LED ist noch ein 	
				{
					for ( DstVar = DstVar1; DstVar <= DstVarN; DstVar ++) // 0.19
					{
						if ((MyAktTime == SwitchVal))
						{
							if (mobaLedLib.Get_Input( DstVar) == INP_ON || mobaLedLib.Get_Input( DstVar) == INP_TURNED_ON)
							{
								if (nRandom-- == 0)
								{
#ifdef _PeterDebug
									SchaltzeitInfo( DstVar, myLedOff, xZufall);
#endif
									mobaLedLib.Set_Input( DstVar,0);
									if (xZufall == 0)		// 02.12.2025
									{
										Pausentimer();		// 02.12.2025
									}
									ToDoCnt --;
									if (ToDoCnt > 0)
									{
										SwitchVal = SwitchVal + xZufall;
										if (SwitchVal > 511)
										{
											SwitchVal = xZufall;
										}
									}
								} 
							}	
						}
					}
				}
				if (ToDoCnt == 0)
				{
				
					if (my_FirstLedStatus == myLedOff)
					{
						my_FirstLedStatus = myLedOn ;
					}
					else
					{
						my_FirstLedStatus = myLedOff ;
					}
				}
			} 
		}
	}

 
	public:

	//----------------------------------
	void setup(MobaLedLib_C& mobaLedLib) // Setup der Funktion
	//----------------------------------
	{
    // hier kommt der Code hin, der beim Starten ausgeführt wird
	
#ifdef _PeterDebug
	flagMitternacht = 0;
	Serial << "P_S- P_Schedule Version " << MyProg_MSG <<  endl;
	if (neuZufall != orgZufall)
	{
		Serial << "P-S-  Zufall-Wert für LED: " << dstVar1 << " verkürzt von " << orgZufall << " auf " << neuZufall <<  " Ticks" << endl; // 0.18 01.01.2025
	}
#endif
	}


	//----------------------------------
	void loop(MobaLedLib_C& mobaLedLib) // Zyklischer Aufruf der Funktion
	//----------------------------------
	{
    // hier kommt der Code hin, der regelmässig ausgeführt wird
		if (mobaLedLib.Trigger20fps > 0)
		{
			Proc_ScheduleMyTime(mobaLedLib);	// Aktuelle Zeit rechnen für P_Schedule-Zeit
			Proc_Schedule(mobaLedLib);			// P_Schedule ausführen
		}
#ifdef _PeterDebug
		if (MyAktTime == 1)
		{
			if (flagMitternacht == 0)
			{
				Serial << "Mitternacht!" << endl;
				flagMitternacht = 1;
			}	
		}
		if (MyAktTime > 1)
		{
			flagMitternacht = 0;
		}
#endif	
	}
};
#endif